# Generated by Django 4.1.5 on 2023-06-10 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('promo', models.IntegerField(default=0)),
                ('new', models.BooleanField()),
                ('sold', models.BooleanField()),
                ('image', models.ImageField(default=None, upload_to='products')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Update Date')),
                ('available_amount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Categoría')),
            ],
        ),
    ]
