# Generated by Django 4.1.5 on 2023-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
